---
site_name: Boardfarm Docs
repo_url: https://github.com/lgirdk/boardfarm

theme:
    name: material
    features:
        - navigation.sections
        - navigation.expand
        - search.suggest
        - search.highlight

plugins:
    - search
    - mkdocstrings

nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Architecture: architecture.md
    - Developer Docs: development.md
    - CHANGELOG: changelog.md
